---
- name: Setup and Configure Apache Web Server
  hosts: all
  become: true
  tasks:
    - name: Install Apache (httpd) package
      ansible.builtin.dnf:
        name: httpd
        state: present
        
    - name: copy jinja2 template
      ansible.builtin.copy:
        src: hello.j2
        dest: /var/www/html/index.html

    - name: Open firewall ports for HTTP and HTTPS
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - http
        - https
      notify: Reload firewalld

    - name: Start and enable the httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

  handlers:
    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
